export default {
    REMOVE_NOTIFICATION:'REMOVE_NOTIFICATION',
    REMOVE_ALL:'REMOVE_ALL',
    START_LOGIN:'START_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED'
}

//action应该是一个瞬时的动作或者是一个状态